<?php

namespace AppBundle\Entity\Banknote\Repository;

/**
 * BanknoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanknoteRepository extends \Doctrine\ORM\EntityRepository
{
}
