# app/config/dev/config.yml
imports:
    - { resource: ../common/config.yml }
    - { resource: parameters.yml }

# Framework
framework:
    router:
        resource: "%kernel.root_dir%/config/dev/routing.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

# Profiler
web_profiler:
    toolbar: true
    intercept_redirects: false

# Logging
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
