# app/config/dev/parameters.yml
parameters:
    # Locale
    locale_dashboard: ru

    # Domains
    domain_dashboard: dashboard.fintech.dev

    # Database
    database_host:     localhost
    database_port:     null
    database_name:     dz
    database_user:     root
    database_password: root

    # Mailer
    mailer_transport: smtp
    mailer_host:      127.0.0.1
    mailer_user:      null
    mailer_password:  null

    # Developers
    developers:
        agency: 'Cheers - Unlimited Web Production'
        link:   'http://cheersunlimited.com.ua'

    # Token
    secret: Something Secret Steers At Us
