# app/config/common/bundle_vich.yml
vich_uploader:
    db_driver: orm

    mappings:
        organization_logo:
            uri_prefix:         /uploads/organization/logos
            upload_destination: %kernel.root_dir%/../www/uploads/organization/logos
            namer:              vich_uploader.namer_uniqid
            delete_on_update:   true
            delete_on_remove:   true
