# app/config/common/config.yml
imports:
    - { resource: security.yml }
    - { resource: services_app.yml }
    - { resource: services_sync.yml }
    - { resource: services_utility.yml }
    - { resource: twig.yml }
    - { resource: bundle_stof.yml }
    - { resource: bundle_jms_di_extra.yml }
    - { resource: bundle_snc_redis.yml }
    - { resource: bundle_vich.yml }

# Framework
framework:
    translator:      { fallbacks: ["%locale_dashboard%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/common/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale_dashboard%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: "snc_redis.session.handler"
    fragments:       ~
    http_method_override: true

# Doctrine
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true

        # Caching
        metadata_cache_driver: redis
        query_cache_driver:    redis


# Swiftmailer
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
