# app/config/common/routing.yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

sync:
    resource: "@SyncBundle/Controller/"
    type:     annotation

employee_dashboard_logout:
    path: /logout
