# app/config/common/security.yml
security:
    encoders:
        AppBundle\Entity\Employee\Employee:
            algorithm: bcrypt
            cost:      15

    role_hierarchy:
        ROLE_EMPLOYEE: [ROLE_USER]

        ROLE_MANAGER:    [ROLE_EMPLOYEE]
        ROLE_ADMIN:      [ROLE_MANAGER]
        ROLE_SUPERADMIN: [ROLE_ADMIN]

    providers:
        employee_provider:
            entity:
                class:    AppBundle:Employee\Employee
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        employee_dashboard:
            host: "%domain_dashboard%"

            anonymous:  ~
            http_basic: ~
            provider:   employee_provider

            form_login:
                login_path:          employee_dashboard_login
                check_path:          employee_dashboard_login_check
                default_target_path: employee_dashboard

                username_parameter: _username
                password_parameter: _password

                csrf_parameter:       _csrf_token
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:   employee_dashboard_logout
                target: employee_dashboard

    access_control:
        -
            host:  "%domain_dashboard%"
            path:  ^/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            host:  "%domain_dashboard%"
            path:  ^/
            roles: ROLE_EMPLOYEE
