# app/config/common/services_sync.yml
services:

    # Event listeners

    sync.listener.security.authorization:
        class: SyncBundle\EventListener\Security\AuthorizationListener
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
            - [setAuthorization, [ "@sync.security.authorization" ]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # Sync

    sync.banking_server.sync.handler:
        class: SyncBundle\Service\BankingServer\Sync\Handler

    sync.banking_server.transfer.formatter:
        class: SyncBundle\Service\BankingServer\Transfer\Formatter

    sync.security.authentication:
        class: SyncBundle\Service\Security\Authentication
        calls:
            - [setPasswordEncoder, [ "@utility.security.password_encoder" ]]

    sync.security.authorization:
        class: SyncBundle\Service\Security\Authorization
        calls:
            - [setPasswordEncoder, [ "@utility.security.password_encoder" ]]
            - [setHashGenerator, [ "@utility.security.hash_generator" ]]

    sync.banking_machine.sync.utility.checksum_calculator:
        class: SyncBundle\Service\BankingMachine\Sync\Utility\ChecksumCalculator

    sync.banking_machine.sync.formatter:
        class: SyncBundle\Service\BankingMachine\Sync\Formatter
        calls:
            - [setChecksumCalculator, [ "@sync.banking_machine.sync.utility.checksum_calculator" ]]

    sync.banking_machine.sync.validator.structure:
        class: SyncBundle\Service\BankingMachine\Sync\Validator\Structure
        calls:
            - [setChecksumCalculator, [ "@sync.banking_machine.sync.utility.checksum_calculator" ]]

    sync.banking_machine.sync.handler:
        class: SyncBundle\Service\BankingMachine\Sync\Handler
        calls:
            - [setManager, [ "@doctrine.orm.entity_manager" ]]
