<?php

namespace AppBundle\Entity\Transfer\Repository;

/**
 * TransferFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferFileRepository extends \Doctrine\ORM\EntityRepository
{
}
