<?php

namespace AppBundle\Entity\NfcTag\Repository;

/**
 * NfcTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NfcTagRepository extends \Doctrine\ORM\EntityRepository
{
}
