<?php

namespace AppBundle\Entity\Transaction\Repository;

/**
 * TransactionFrozenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionFrozenRepository extends \Doctrine\ORM\EntityRepository
{
}
